name: CI
on: [push, pull_request]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        compiler: [gcc, clang]
        penger: ["", "PENGER=1"]
    steps:
      - uses: actions/checkout@v1
      - name: install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -qq libsdl2-dev
      - name: build sowon
        run: |
          make ${{ matrix.penger }}
        env:
          CC: ${{ matrix.compiler }}
  build-macos:
    runs-on: macOS-latest
    strategy:
      matrix:
        penger: ["", "PENGER=1"]
    steps:
      - uses: actions/checkout@v1
      - name: install dependencies
        run: brew install sdl2 pkg-config
      - name: build sowon
        run: |
          make ${{ matrix.penger }}
        env:
          CC: clang
  build-windows-msvc:
    runs-on: windows-latest
    strategy:
      matrix:
        penger: ["", "PENGER"]
    steps:
      - uses: actions/checkout@v1
        # this runs vcvarsall for us, so we get the MSVC toolchain in PATH.
      - uses: seanmiddleditch/gha-setup-vsdevenv@master
      - name: download sdl2
        run: |
          curl -fsSL -o SDL2-devel-2.0.12-VC.zip https://www.libsdl.org/release/SDL2-devel-2.0.12-VC.zip
          tar -xf SDL2-devel-2.0.12-VC.zip
          mv SDL2-2.0.12 SDL2
      - name: build sowon
        shell: cmd
        run: |
          build_msvc.bat ${{ matrix.penger }}

  build-freebsd:
    runs-on: ubuntu-latest
    name: FreeBSD LLVM Clang build
    strategy:
      matrix:
        penger: ["", "PENGER=1"]
    steps:
      - uses: actions/checkout@v2
      - name: Build on FreeBSD
        id: build
        uses: vmactions/freebsd-vm@v1
        with:
          usesh: true
          prepare: pkg install -y sdl2 pkgconf
          run: |
            freebsd-version
            make ${{ matrix.penger }}
